"""add interactive training persistence

Revision ID: 0010_interactive_training
Revises: 0009_assignment_completion_rollout
Create Date: 2026-08-29 11:46:31.570664
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010_interactive_training"
down_revision: str | None = "0009_assignment_completion_rollout"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_generation_rules",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("domain_type", sa.String(length=32), server_default="menu", nullable=False),
        sa.Column("mechanic", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "domain_type = 'menu'", name=op.f("ck_question_generation_rules_domain_type_menu")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(configuration) = 'object'",
            name=op.f("ck_question_generation_rules_configuration_object"),
        ),
        sa.CheckConstraint(
            "mechanic IN ('single_choice', 'multiple_choice', 'matching', "
            "'ordering', 'assembly', 'recognition')",
            name=op.f("ck_question_generation_rules_mechanic_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'retired')",
            name=op.f("ck_question_generation_rules_status_allowed"),
        ),
        sa.CheckConstraint(
            "length(btrim(code)) BETWEEN 1 AND 100",
            name=op.f("ck_question_generation_rules_code_length"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_question_generation_rules_version_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_generation_rules")),
        sa.UniqueConstraint("code", "version", name="uq_question_generation_rules_code_version"),
    )
    op.create_table(
        "questions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id", "organization_id"],
            ["locations.id", "locations.organization_id"],
            name="fk_questions_location_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("id", "organization_id", "location_id", name="uq_questions_scope"),
    )
    op.create_table(
        "assessments",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("training_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("assessment_type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "assessment_type IN ('interactive_training', "
            "'whole_menu_knowledge_check', 'menu_final_exam')",
            name=op.f("ck_assessments_assessment_type_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_assessments_lesson_id_lessons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["training_id", "organization_id", "location_id"],
            ["trainings.id", "trainings.organization_id", "trainings.location_id"],
            name="fk_assessments_training_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
        sa.UniqueConstraint("id", "organization_id", "location_id", name="uq_assessments_scope"),
        sa.UniqueConstraint("lesson_id", "assessment_type", name="uq_assessments_lesson_type"),
    )
    op.create_table(
        "assessment_versions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("training_version_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("lesson_version_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("question_count", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "feedback_policy", sa.String(length=16), server_default="immediate", nullable=False
        ),
        sa.Column(
            "sampling_configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("published_by_user_id", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "feedback_policy = 'immediate'",
            name=op.f("ck_assessment_versions_interactive_feedback_policy"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(sampling_configuration) = 'object'",
            name=op.f("ck_assessment_versions_sampling_configuration_object"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_assessment_versions_status_allowed"),
        ),
        sa.CheckConstraint(
            "question_count = 5", name=op.f("ck_assessment_versions_interactive_question_count")
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_assessment_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id", "organization_id", "location_id"],
            ["assessments.id", "assessments.organization_id", "assessments.location_id"],
            name="fk_assessment_versions_assessment_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lesson_version_id", "lesson_id"],
            ["lesson_versions.id", "lesson_versions.lesson_id"],
            name="fk_assessment_versions_lesson_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_assessment_versions_published_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["training_version_id", "organization_id", "location_id"],
            [
                "training_versions.id",
                "training_versions.organization_id",
                "training_versions.location_id",
            ],
            name="fk_assessment_versions_training_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_versions")),
        sa.UniqueConstraint(
            "assessment_id", "version_number", name="uq_assessment_versions_number"
        ),
        sa.UniqueConstraint("id", "assessment_id", name="uq_assessment_versions_assessment_scope"),
    )
    op.create_index(
        "ix_assessment_versions_training_lesson_status",
        "assessment_versions",
        ["training_version_id", "lesson_version_id", "status"],
        unique=False,
    )
    op.create_table(
        "question_candidates",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("generation_rule_id", sa.UUID(), nullable=False),
        sa.Column("training_version_id", sa.UUID(), nullable=False),
        sa.Column("lesson_version_id", sa.UUID(), nullable=False),
        sa.Column("mechanic", sa.String(length=32), nullable=False),
        sa.Column("prompt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answer_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_critical", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="needs_review", nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'needs_review' AND reviewed_by_user_id IS NULL "
            "AND reviewed_at IS NULL) OR "
            "(status IN ('approved', 'rejected', 'stale'))",
            name=op.f("ck_question_candidates_review_state_match"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(answer_payload) = 'object'",
            name=op.f("ck_question_candidates_answer_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(explanation_payload) = 'object'",
            name=op.f("ck_question_candidates_explanation_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(prompt_payload) = 'object'",
            name=op.f("ck_question_candidates_prompt_payload_object"),
        ),
        sa.CheckConstraint(
            "mechanic IN ('single_choice', 'multiple_choice', 'matching', "
            "'ordering', 'assembly', 'recognition')",
            name=op.f("ck_question_candidates_mechanic_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('needs_review', 'approved', 'rejected', 'stale')",
            name=op.f("ck_question_candidates_status_allowed"),
        ),
        sa.CheckConstraint(
            "length(source_fingerprint) = 64",
            name=op.f("ck_question_candidates_source_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "revision >= 0", name=op.f("ck_question_candidates_revision_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["generation_rule_id"],
            ["question_generation_rules.id"],
            name=op.f("fk_question_candidates_generation_rule_id_question_generation_rules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lesson_version_id"],
            ["lesson_versions.id"],
            name=op.f("fk_question_candidates_lesson_version_id_lesson_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id", "organization_id"],
            ["locations.id", "locations.organization_id"],
            name="fk_question_candidates_location_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_question_candidates_reviewed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["training_version_id", "organization_id", "location_id"],
            [
                "training_versions.id",
                "training_versions.organization_id",
                "training_versions.location_id",
            ],
            name="fk_question_candidates_training_version_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_candidates")),
        sa.UniqueConstraint(
            "generation_rule_id",
            "lesson_version_id",
            "source_fingerprint",
            name="uq_question_candidates_generation_fingerprint",
        ),
        sa.UniqueConstraint(
            "id", "organization_id", "location_id", name="uq_question_candidates_scope"
        ),
    )
    op.create_index(
        "ix_question_candidates_review_queue",
        "question_candidates",
        ["organization_id", "location_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "assessment_attempts",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("training_id", sa.UUID(), nullable=False),
        sa.Column("employee_profile_id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("assessment_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="in_progress", nullable=False),
        sa.Column("presentation_locale", sa.String(length=8), nullable=False),
        sa.Column("question_count", sa.Integer(), server_default="5", nullable=False),
        sa.Column("snapshot_schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'in_progress' AND completed_at IS NULL) OR "
            "(status = 'completed' AND completed_at IS NOT NULL) OR "
            "(status IN ('expired', 'invalidated'))",
            name=op.f("ck_assessment_attempts_completion_state_match"),
        ),
        sa.CheckConstraint(
            "presentation_locale IN ('uk', 'en')",
            name=op.f("ck_assessment_attempts_locale_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'expired', 'invalidated')",
            name=op.f("ck_assessment_attempts_status_allowed"),
        ),
        sa.CheckConstraint(
            "expires_at > started_at", name=op.f("ck_assessment_attempts_expiry_after_start")
        ),
        sa.CheckConstraint(
            "question_count = 5", name=op.f("ck_assessment_attempts_question_count_five")
        ),
        sa.CheckConstraint(
            "snapshot_schema_version >= 1",
            name=op.f("ck_assessment_attempts_snapshot_schema_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_version_id"],
            ["assessment_versions.id"],
            name=op.f("fk_assessment_attempts_assessment_version_id_assessment_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id", "organization_id", "location_id", "training_id"],
            [
                "training_assignments.id",
                "training_assignments.organization_id",
                "training_assignments.location_id",
                "training_assignments.training_id",
            ],
            name="fk_assessment_attempts_assignment_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_profile_id", "organization_id"],
            ["employee_profiles.id", "employee_profiles.organization_id"],
            name="fk_assessment_attempts_employee_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_attempts")),
        sa.UniqueConstraint(
            "id",
            "organization_id",
            "location_id",
            "training_id",
            name="uq_assessment_attempts_scope",
        ),
    )
    op.create_index(
        "ix_assessment_attempts_employee_completed",
        "assessment_attempts",
        ["employee_profile_id", "assessment_version_id", "completed_at"],
        unique=False,
    )
    op.create_index(
        "uq_assessment_attempts_active",
        "assessment_attempts",
        ["employee_profile_id", "assignment_id", "assessment_version_id"],
        unique=True,
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.create_table(
        "assessment_readiness",
        sa.Column("assessment_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="processing", nullable=False),
        sa.Column("eligible_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("required_count", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "coverage_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "rotation_supported", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("basis_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "blocking_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "warning_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(blocking_codes) = 'array'",
            name=op.f("ck_assessment_readiness_blocking_codes_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(coverage_evidence) = 'object'",
            name=op.f("ck_assessment_readiness_coverage_evidence_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(warning_codes) = 'array'",
            name=op.f("ck_assessment_readiness_warning_codes_array"),
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'ready', 'warning', 'blocked')",
            name=op.f("ck_assessment_readiness_status_allowed"),
        ),
        sa.CheckConstraint(
            "eligible_count >= 0 AND required_count = 5",
            name=op.f("ck_assessment_readiness_counts_valid"),
        ),
        sa.CheckConstraint(
            "length(basis_fingerprint) = 64",
            name=op.f("ck_assessment_readiness_basis_fingerprint_length"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_version_id"],
            ["assessment_versions.id"],
            name=op.f("fk_assessment_readiness_assessment_version_id_assessment_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_readiness")),
        sa.UniqueConstraint("assessment_version_id", name="uq_assessment_readiness_version"),
    )
    op.create_table(
        "assessment_version_translations",
        sa.Column("assessment_version_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "locale IN ('uk', 'en')", name=op.f("ck_assessment_version_translations_locale_allowed")
        ),
        sa.CheckConstraint(
            "length(btrim(title)) BETWEEN 1 AND 200",
            name=op.f("ck_assessment_version_translations_title_length"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_version_id"],
            ["assessment_versions.id"],
            name=op.f(
                "fk_assessment_version_translations_assessment_version_id_assessment_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_version_translations")),
        sa.UniqueConstraint(
            "assessment_version_id", "locale", name="uq_assessment_version_translations_locale"
        ),
    )
    op.create_table(
        "question_versions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="published", nullable=False),
        sa.Column("mechanic", sa.String(length=32), nullable=False),
        sa.Column("prompt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grading_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_critical", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("published_by_user_id", sa.UUID(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(explanation_payload) = 'object'",
            name=op.f("ck_question_versions_explanation_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(grading_payload) = 'object'",
            name=op.f("ck_question_versions_grading_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(prompt_payload) = 'object'",
            name=op.f("ck_question_versions_prompt_payload_object"),
        ),
        sa.CheckConstraint(
            "mechanic IN ('single_choice', 'multiple_choice', 'matching', "
            "'ordering', 'assembly', 'recognition')",
            name=op.f("ck_question_versions_mechanic_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('published', 'stale', 'archived')",
            name=op.f("ck_question_versions_status_allowed"),
        ),
        sa.CheckConstraint(
            "length(source_fingerprint) = 64",
            name=op.f("ck_question_versions_source_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_question_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id", "organization_id", "location_id"],
            [
                "question_candidates.id",
                "question_candidates.organization_id",
                "question_candidates.location_id",
            ],
            name="fk_question_versions_candidate_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_question_versions_published_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_id", "organization_id", "location_id"],
            ["questions.id", "questions.organization_id", "questions.location_id"],
            name="fk_question_versions_question_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_versions")),
        sa.UniqueConstraint(
            "id", "organization_id", "location_id", name="uq_question_versions_scope"
        ),
        sa.UniqueConstraint("id", "question_id", name="uq_question_versions_question_scope"),
        sa.UniqueConstraint("question_id", "version_number", name="uq_question_versions_number"),
    )
    op.create_index(
        "ix_question_versions_scope_status",
        "question_versions",
        ["organization_id", "location_id", "status"],
        unique=False,
    )
    op.create_table(
        "assessment_question_pools",
        sa.Column("assessment_version_id", sa.UUID(), nullable=False),
        sa.Column("question_version_id", sa.UUID(), nullable=False),
        sa.Column("coverage_key", sa.String(length=200), nullable=False),
        sa.Column("mechanic", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Integer(), server_default="1", nullable=False),
        sa.Column("eligible", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("exclusion_reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(eligible = true AND exclusion_reason IS NULL) OR "
            "(eligible = false AND exclusion_reason IS NOT NULL)",
            name=op.f("ck_assessment_question_pools_eligibility_reason_match"),
        ),
        sa.CheckConstraint(
            "weight BETWEEN 1 AND 100", name=op.f("ck_assessment_question_pools_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["assessment_version_id"],
            ["assessment_versions.id"],
            name=op.f("fk_assessment_question_pools_assessment_version_id_assessment_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_assessment_question_pools_question_version_id_question_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_question_pools")),
        sa.UniqueConstraint(
            "assessment_version_id",
            "question_version_id",
            name="uq_assessment_question_pools_question",
        ),
    )
    op.create_index(
        "ix_assessment_question_pools_eligible",
        "assessment_question_pools",
        ["assessment_version_id", "eligible"],
        unique=False,
    )
    op.create_table(
        "attempt_device_leases",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("generation", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "generation >= 1", name=op.f("ck_attempt_device_leases_generation_positive")
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_attempt_device_leases_attempt_id_assessment_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_attempt_device_leases_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_device_leases")),
        sa.UniqueConstraint("attempt_id", name="uq_attempt_device_leases_attempt"),
    )
    op.create_table(
        "attempt_questions",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("question_version_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("mechanic", sa.String(length=32), nullable=False),
        sa.Column("prompt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grading_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_critical", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("coverage_key", sa.String(length=200), nullable=False),
        sa.Column("presentation_locale", sa.String(length=8), nullable=False),
        sa.Column("provenance_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(explanation_payload) = 'object'",
            name=op.f("ck_attempt_questions_explanation_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(grading_payload) = 'object'",
            name=op.f("ck_attempt_questions_grading_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(prompt_payload) = 'object'",
            name=op.f("ck_attempt_questions_prompt_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(provenance_snapshot) = 'object'",
            name=op.f("ck_attempt_questions_provenance_snapshot_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(version_snapshot) = 'object'",
            name=op.f("ck_attempt_questions_version_snapshot_object"),
        ),
        sa.CheckConstraint(
            "mechanic IN ('single_choice', 'multiple_choice', 'matching', "
            "'ordering', 'assembly', 'recognition')",
            name=op.f("ck_attempt_questions_mechanic_allowed"),
        ),
        sa.CheckConstraint(
            "position BETWEEN 0 AND 4", name=op.f("ck_attempt_questions_position_range")
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_attempt_questions_attempt_id_assessment_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_attempt_questions_question_version_id_question_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_questions")),
        sa.UniqueConstraint("attempt_id", "position", name="uq_attempt_questions_position"),
        sa.UniqueConstraint(
            "attempt_id", "question_version_id", name="uq_attempt_questions_version"
        ),
        sa.UniqueConstraint("id", "attempt_id", name="uq_attempt_questions_attempt_scope"),
    )
    op.create_index(
        "ix_attempt_questions_attempt_position",
        "attempt_questions",
        ["attempt_id", "position"],
        unique=False,
    )
    op.create_table(
        "attempt_results",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("total_count", sa.Integer(), server_default="5", nullable=False),
        sa.Column("score_basis_points", sa.Integer(), nullable=False),
        sa.Column("knowledge_level", sa.String(length=16), nullable=False),
        sa.Column("pass_status", sa.String(length=16), nullable=True),
        sa.Column("critical_error_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "section_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(section_breakdown) = 'object'",
            name=op.f("ck_attempt_results_section_breakdown_object"),
        ),
        sa.CheckConstraint(
            "knowledge_level IN ('very_weak', 'weak', 'good', 'strong')",
            name=op.f("ck_attempt_results_knowledge_level_allowed"),
        ),
        sa.CheckConstraint(
            "correct_count BETWEEN 0 AND total_count",
            name=op.f("ck_attempt_results_correct_count_range"),
        ),
        sa.CheckConstraint(
            "critical_error_count BETWEEN 0 AND total_count",
            name=op.f("ck_attempt_results_critical_error_count_range"),
        ),
        sa.CheckConstraint(
            "pass_status IS NULL", name=op.f("ck_attempt_results_interactive_pass_status_null")
        ),
        sa.CheckConstraint(
            "score_basis_points BETWEEN 0 AND 10000", name=op.f("ck_attempt_results_score_range")
        ),
        sa.CheckConstraint("total_count = 5", name=op.f("ck_attempt_results_total_count_five")),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_attempt_results_attempt_id_assessment_attempts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_results")),
        sa.UniqueConstraint("attempt_id", name="uq_attempt_results_attempt"),
    )
    op.create_table(
        "question_options",
        sa.Column("question_version_id", sa.UUID(), nullable=False),
        sa.Column("stable_key", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_correct", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'", name=op.f("ck_question_options_payload_object")
        ),
        sa.CheckConstraint(
            "length(btrim(stable_key)) BETWEEN 1 AND 100",
            name=op.f("ck_question_options_stable_key_length"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_question_options_position_nonnegative")),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_question_options_question_version_id_question_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_options")),
        sa.UniqueConstraint("question_version_id", "position", name="uq_question_options_position"),
        sa.UniqueConstraint(
            "question_version_id", "stable_key", name="uq_question_options_stable_key"
        ),
    )
    op.create_table(
        "question_source_links",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("question_version_id", sa.UUID(), nullable=False),
        sa.Column("source_role", sa.String(length=32), nullable=False),
        sa.Column("menu_item_version_id", sa.UUID(), nullable=True),
        sa.Column("menu_item_version_component_id", sa.UUID(), nullable=True),
        sa.Column("menu_item_version_allergen_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_role IN ('correct_fact', 'distractor_basis', "
            "'explanation_source', 'critical_fact')",
            name=op.f("ck_question_source_links_source_role_allowed"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(menu_item_version_id, menu_item_version_component_id, "
            "menu_item_version_allergen_id) = 1",
            name=op.f("ck_question_source_links_exactly_one_source"),
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_version_allergen_id"],
            ["menu_item_version_allergens.id"],
            name=op.f(
                "fk_question_source_links_menu_item_version_allergen_id_menu_item_version_allergens"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_version_component_id"],
            ["menu_item_version_components.id"],
            name=op.f(
                "fk_question_source_links_menu_item_version_component_id_menu_item_version_components"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_version_id"],
            ["menu_item_versions.id"],
            name=op.f("fk_question_source_links_menu_item_version_id_menu_item_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id", "organization_id", "location_id"],
            [
                "question_versions.id",
                "question_versions.organization_id",
                "question_versions.location_id",
            ],
            name="fk_question_source_links_question_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_source_links")),
    )
    op.create_index(
        "ix_question_source_links_question_role",
        "question_source_links",
        ["question_version_id", "source_role"],
        unique=False,
    )
    op.create_table(
        "question_version_translations",
        sa.Column("question_version_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("prompt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(explanation_payload) = 'object'",
            name=op.f("ck_question_version_translations_explanation_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(prompt_payload) = 'object'",
            name=op.f("ck_question_version_translations_prompt_payload_object"),
        ),
        sa.CheckConstraint(
            "locale IN ('uk', 'en')", name=op.f("ck_question_version_translations_locale_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_question_version_translations_question_version_id_question_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_version_translations")),
        sa.UniqueConstraint(
            "question_version_id", "locale", name="uq_question_version_translations_locale"
        ),
    )
    op.create_table(
        "attempt_options",
        sa.Column("attempt_question_id", sa.UUID(), nullable=False),
        sa.Column("source_option_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'", name=op.f("ck_attempt_options_payload_object")
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_attempt_options_position_nonnegative")),
        sa.ForeignKeyConstraint(
            ["attempt_question_id"],
            ["attempt_questions.id"],
            name=op.f("fk_attempt_options_attempt_question_id_attempt_questions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_option_id"],
            ["question_options.id"],
            name=op.f("fk_attempt_options_source_option_id_question_options"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_options")),
        sa.UniqueConstraint("attempt_question_id", "position", name="uq_attempt_options_position"),
        sa.UniqueConstraint(
            "attempt_question_id", "source_option_id", name="uq_attempt_options_source"
        ),
    )
    op.create_table(
        "question_option_translations",
        sa.Column("question_option_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'",
            name=op.f("ck_question_option_translations_payload_object"),
        ),
        sa.CheckConstraint(
            "locale IN ('uk', 'en')", name=op.f("ck_question_option_translations_locale_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["question_option_id"],
            ["question_options.id"],
            name=op.f("fk_question_option_translations_question_option_id_question_options"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_option_translations")),
        sa.UniqueConstraint(
            "question_option_id", "locale", name="uq_question_option_translations_locale"
        ),
    )
    op.create_table(
        "submitted_answers",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("attempt_question_id", sa.UUID(), nullable=False),
        sa.Column("answer_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "is_critical_error", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(answer_payload) = 'object'",
            name=op.f("ck_submitted_answers_payload_object"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_submitted_answers_attempt_id_assessment_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_question_id", "attempt_id"],
            ["attempt_questions.id", "attempt_questions.attempt_id"],
            name="fk_submitted_answers_question_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submitted_answers")),
        sa.UniqueConstraint(
            "attempt_id", "attempt_question_id", name="uq_submitted_answers_attempt_question"
        ),
        sa.UniqueConstraint(
            "attempt_id", "idempotency_key", name="uq_submitted_answers_idempotency"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("submitted_answers")
    op.drop_table("question_option_translations")
    op.drop_table("attempt_options")
    op.drop_table("question_version_translations")
    op.drop_index("ix_question_source_links_question_role", table_name="question_source_links")
    op.drop_table("question_source_links")
    op.drop_table("question_options")
    op.drop_table("attempt_results")
    op.drop_index("ix_attempt_questions_attempt_position", table_name="attempt_questions")
    op.drop_table("attempt_questions")
    op.drop_table("attempt_device_leases")
    op.drop_index("ix_assessment_question_pools_eligible", table_name="assessment_question_pools")
    op.drop_table("assessment_question_pools")
    op.drop_index("ix_question_versions_scope_status", table_name="question_versions")
    op.drop_table("question_versions")
    op.drop_table("assessment_version_translations")
    op.drop_table("assessment_readiness")
    op.drop_index(
        "uq_assessment_attempts_active",
        table_name="assessment_attempts",
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.drop_index("ix_assessment_attempts_employee_completed", table_name="assessment_attempts")
    op.drop_table("assessment_attempts")
    op.drop_index("ix_question_candidates_review_queue", table_name="question_candidates")
    op.drop_table("question_candidates")
    op.drop_index("ix_assessment_versions_training_lesson_status", table_name="assessment_versions")
    op.drop_table("assessment_versions")
    op.drop_table("assessments")
    op.drop_table("questions")
    op.drop_table("question_generation_rules")
    # ### end Alembic commands ###
